#!/bin/bash

# Step 1: Install dependencies for compiling xmrig
sudo echo "Installing dependencies..."
sudo apt update
sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev jq curl

# Step 2: Clone the xmrig repository
echo "Cloning XMRig repository..."
git clone https://github.com/xmrig/xmrig.git
cd xmrig

# Step 3: Compile xmrig
echo "Compiling XMRig..."
mkdir build
cd build
cmake ..
make
mkdir ../../miner
cp xmrig ../../miner
cd ../../miner
